# Site settings
title: Just Here                  
SEOTitle: 陈敏的博客 | Right Here
header-img: img/post-bg-desk.jpg
email: minchen708@gmail.com
description: "First say to yourself what you would be, and then do what you have to do."
keyword: "Right, Right Here, 陈敏的博客, chenminmin, 陈敏, Web"
url: "http://crazy-chen.github.io"          # my host, for absolute URL
baseurl: ""      # for example, '/blog' if my blog hosted on 'host/blog'
github_repo: "https://github.com/Crazy-chen/Crazy-chen.github.io.git" # my code repository

# Sidebar settings 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "The useless men are those who never change with the years."
sidebar-avatar: /img/my_avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings 社交账号设置
RSS: false
# weibo_username:      
zhihu_username:     陈敏
github_username:    Crazy-chen
facebook_username:  Crazychenmin
jianshu_username:   e74a712afd40
#twitter_username:    




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
disqus_username: Crazychenmin

# 多说 将于2017年6月1日正式关停服务，建议使用 Disqus（http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241）
# Duoshuo settings
# duoshuo_username: qiubaiying
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-111117685-1'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "FreeCodeCamp",
        href: "https://www.freecodecamp.org/crazy-chen"
    },{
        title: "CodePen",
        href: "https://codepen.io/chenmin/"
    },{
        title: "Stack Overflow",
        href: "https://stackoverflow.com/users/9039938/chen-min"
    },{
        title: "Youtube",
        href: "https://www.youtube.com/"
    }
]
